- name: Varaiables is pulled from another file
  hosts: local
  connection: local
  vars_files:
  - vars-files.yaml
  Tasks:
  - name: Varaiables is pulled from another file
    ansible.builtin.debug:
     msg: "Hello courseName:{{courseName}} and Duration:{{Duration}} and Trainer:{{Trainer}}"