- name: Varaiables is pulled from another file
  hosts: local
  connection: local
  vars_files:
  - vars-files.yaml
  tasks:
   - name: Varaiables is pulled from another file
     ansible.builtin.debug:
      msg: "Hello courseName:{{ courseName }},Duration:{{ Duration }},Trainer:{{ Trainer }}"