- name: vars-files
  hosts: local
  connection: local
  vars-files:
  - vars-files.yaml
  
  Tasks:
  - name: vars-files
    ansible.builtin.debug:
     msg: "Hello courseName: {{ courseName }} and Duration:{{ Duration }} and Trainer:{{ Trainer }}"