- name: nginx install
  hosts: frontend
  become: yes
  tasks:
   - name: dnf install nginx
     ansible.builtin.package:
      name: nginx
      state: present

   - name: start service
     ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      